### ISSUE TITLE
Create a release compatible with WoWUp

### ISSUE THREAD

**Issue by SpareSimian** [awls99/Random-Hearthstone-Toy-Continued#27]
[WoWUp](https://wowup.io/) can install addons from Wago, WoWInterface, and directly from GitHub as well as from Curse. I use this procedure to make my addons work with it:

https://gist.github.com/SpareSimian/c91f5f0261a11f030c363553f685ab71

**Comment by awls99** [comment]
honestly thought wowup had died some time ago, I'll take a look into it soon

**Comment by SpareSimian** [comment]
Thanks. It's fast and ad-free so I don't have to worry about getting infected by malware in an ad. I used to use Ajour, which is even faster, but the dev stopped working on it. 

The BigWigs script looked complicated at first but I found it was pretty easy to integrate once I understood what it does, so I wrote up that gist with my experience.

**Comment by awls99** [comment]
Hey, I kinda forgot about this, I've been using WoWUp myself for a about 2 months now and I update myself via there, so it's already working, at least it's using the version that gets from Curse :man_shrugging: 
not sure if it's worth bothering pushing to the other platforms.
I will if this issue gets a couple of thumbs, otherwise I'm closing this for now
